import pytest
from tests.conftest import register_and_login, auth_headers


# ──────────────────────── helpers ────────────────────────

async def _create_transaction_and_get_alert(client, token, user_id):
    """Submit a high-risk transaction so the system auto-creates an alert,
    then return the first alert id (if any)."""
    tx_payload = {
        "transaction_id": "TXN_ALERT_TEST",
        "card_id": "CARD_ALERT",
        "amount": 99000.00,
        "currency": "USD",
        "merchant_id": "MERCH_ALERT",
        "merchant_category": "electronics",
        "country_code": "XX",          # unusual country to trigger risk
        "city": "Nowhere",
        "ip_address": "10.0.0.1",
        "device_fingerprint": "fp_alert",
        "timestamp": "2024-01-01T12:00:00Z",
        "user_id": str(user_id),
    }
    resp = await client.post(
        "/api/v1/transactions/assess",
        json=tx_payload,
        headers=auth_headers(token),
    )
    assert resp.status_code == 200

    # Fetch alerts
    resp = await client.get("/api/v1/alerts/?page=1&limit=50", headers=auth_headers(token))
    alerts = resp.json().get("items", [])
    return alerts[0]["id"] if alerts else None


# ──────────────────────────── GET /api/v1/alerts/ ────────────────────────────

@pytest.mark.asyncio
async def test_list_alerts_empty(client):
    """Listing alerts with none present should return empty list."""
    _, token = await register_and_login(client, email="alerts_empty@test.com")
    response = await client.get(
        "/api/v1/alerts/?page=1&limit=20",
        headers=auth_headers(token),
    )
    assert response.status_code == 200
    data = response.json()
    assert "items" in data
    assert isinstance(data["items"], list)
    assert "total" in data


@pytest.mark.asyncio
async def test_list_alerts_unauthenticated(client):
    """Listing alerts without auth should fail."""
    response = await client.get("/api/v1/alerts/")
    assert response.status_code in (401, 403)


@pytest.mark.asyncio
async def test_list_alerts_after_high_risk_transaction(client):
    """After a high-risk transaction an alert should be created."""
    user_id, token = await register_and_login(client, email="alert_txn@test.com")
    alert_id = await _create_transaction_and_get_alert(client, token, user_id)
    # alert_id might be None if the risk engine doesn't flag it – that's okay
    # We at least validate the endpoint works
    response = await client.get(
        "/api/v1/alerts/?page=1&limit=20",
        headers=auth_headers(token),
    )
    assert response.status_code == 200


@pytest.mark.asyncio
async def test_list_alerts_pagination(client):
    """Pagination params should be respected."""
    _, token = await register_and_login(client, email="alerts_page@test.com")
    response = await client.get(
        "/api/v1/alerts/?page=1&limit=5",
        headers=auth_headers(token),
    )
    assert response.status_code == 200
    data = response.json()
    assert data["page"] == 1
    assert data["limit"] == 5


# ──────────────────────────── GET /api/v1/alerts/{alert_id} ────────────────────────────

@pytest.mark.asyncio
async def test_get_alert_not_found(client):
    """Getting a non-existent alert should return 404."""
    _, token = await register_and_login(client, email="alert404@test.com")
    response = await client.get(
        "/api/v1/alerts/00000000-0000-0000-0000-000000000001",
        headers=auth_headers(token),
    )
    assert response.status_code == 404


@pytest.mark.asyncio
async def test_get_alert_by_id(client):
    """If an alert exists, we should be able to fetch it by ID."""
    user_id, token = await register_and_login(client, email="alert_get@test.com")
    alert_id = await _create_transaction_and_get_alert(client, token, user_id)

    if alert_id is None:
        pytest.skip("No alert was generated by the risk engine for this transaction")

    response = await client.get(
        f"/api/v1/alerts/{alert_id}",
        headers=auth_headers(token),
    )
    assert response.status_code == 200
    data = response.json()
    assert data["id"] == alert_id


@pytest.mark.asyncio
async def test_get_alert_unauthenticated(client):
    """Getting an alert without auth should fail."""
    response = await client.get("/api/v1/alerts/00000000-0000-0000-0000-000000000001")
    assert response.status_code in (401, 403)


# ──────────────────────────── POST /api/v1/alerts/{alert_id}/assign ────────────────────────────

@pytest.mark.asyncio
async def test_assign_alert(client):
    """Analyst should be able to assign an alert to a user."""
    user_id, token = await register_and_login(client, email="assign_alert@test.com")
    alert_id = await _create_transaction_and_get_alert(client, token, user_id)

    if alert_id is None:
        pytest.skip("No alert generated")

    response = await client.post(
        f"/api/v1/alerts/{alert_id}/assign?user_id={user_id}",
        headers=auth_headers(token),
    )
    # analyst role has permission (require_analyst allows admin + analyst)
    assert response.status_code == 200


@pytest.mark.asyncio
async def test_assign_alert_unauthenticated(client):
    """Assigning without auth should fail."""
    fake_uuid = "00000000-0000-0000-0000-000000000001"
    response = await client.post(
        f"/api/v1/alerts/{fake_uuid}/assign?user_id={fake_uuid}",
    )
    assert response.status_code in (401, 403)


# ──────────────────────────── POST /api/v1/alerts/{alert_id}/resolve ────────────────────────────

@pytest.mark.asyncio
async def test_resolve_alert(client):
    """Analyst should be able to resolve an open alert."""
    user_id, token = await register_and_login(client, email="resolve_alert@test.com")
    alert_id = await _create_transaction_and_get_alert(client, token, user_id)

    if alert_id is None:
        pytest.skip("No alert generated")

    response = await client.post(
        f"/api/v1/alerts/{alert_id}/resolve",
        json={
            "status": "resolved",
            "resolution_notes": "Verified as legit transaction"
        },
        headers=auth_headers(token),
    )
    assert response.status_code == 200


@pytest.mark.asyncio
async def test_resolve_alert_false_positive(client):
    """Marking an alert as false positive should work."""
    user_id, token = await register_and_login(client, email="fp_alert@test.com")
    alert_id = await _create_transaction_and_get_alert(client, token, user_id)

    if alert_id is None:
        pytest.skip("No alert generated")

    response = await client.post(
        f"/api/v1/alerts/{alert_id}/resolve",
        json={
            "status": "false_positive",
            "resolution_notes": "False alarm"
        },
        headers=auth_headers(token),
    )
    assert response.status_code == 200


@pytest.mark.asyncio
async def test_resolve_alert_unauthenticated(client):
    """Resolving without auth should fail."""
    fake_uuid = "00000000-0000-0000-0000-000000000001"
    response = await client.post(
        f"/api/v1/alerts/{fake_uuid}/resolve",
        json={"status": "resolved", "resolution_notes": "test"},
    )
    assert response.status_code in (401, 403)
